# playbook_install.yml
---

- hosts: gateway
  become: yes
  user: sysadm

  tasks:
  - name: Update APT package cache
    apt: update_cache=yes

  - name: Install Monitoring tools
    apt: pkg={{ item }} state=present
    with_items:
    - htop
    - iotop
    - sysstat
    - dstat
    - iftop

  - name: Install Networking tools
    apt: pkg={{ item }} state=present
    with_items:
    - iperf
    - nmap
    - tcpdump

  - name: Install Debugging tools
    apt: pkg={{ item }} state=present
    with_items:
    - dtrace

  - name: Install services & apps
    apt: pkg={{ item }} state=present
    with_items:
    - ssh
    - sudo
    - isc-dhcp-server
    - fish
#- shinken

# Configure shell fish
  - block: 
    - name: Get fish path  
      command: which fish
      register: fish

    - name: Setup fish as shell
      user: name="{{ item }}" shell="{{ fish.stdout }}"
      become_user: "{{ item }}"
      with_items:
      - {{ user_name }}
      - root

# Configure sudoer
  - name: Setup sudo for user
    set_fact: username={{ user_name }}
    lineinfile: "dest=/etc/sudoers state=present regexp='^%username' line='%username ALL=(ALL) NOPASSWD: ALL'"

# Configure Grub
  # - name: Setup grub resolution 
  #   lineinfile: "dest=/etc/default/grub state=present regexp='^%GRUB_CMDLINE_LINUX_DEFAULT' line='%username ALL=(ALL) NOPASSWD: ALL'"





  - name: Install library
    apt: pkg={{ item }} state=present
    with_items:
    - libusb-dev
    - libnfc-bin

  - name: Git repository RFIDIoT
    git:  repo=https://github.com/AdamLaurie/RFIDIOt.git dest=/root/sources/rfidiot force=yes

  - name: Change file right
    file: path=/root/sources/rfidiot/setup.py mode=744

  - name: Install RFIDIoT
    command: 'python setup.py install'
    args:
      chdir: /root/sources/rfidiot


  - name: Install requests module
    pip: name=requests

  - name: Create directory
    file: path=/root/scripts state=directory mode=744

  - name: Copy detectTrain.py
    copy: src=detectTrain.py
          dest=/root/scripts/detectTrain.py
          owner=root
          group=root
          mode=744
          force=yes

  - name: Copy isRunning.sh
    copy: src=isRunning.sh
          dest=/root/scripts/isRunning.sh
          owner=root
          group=root
          mode=744
          force=yes

  - name: Cron activation
    cron: name=isRunning minute="*" job="/root/scripts/isRunning.sh detectTrain"

  # - name: Configure Wi-Fi
  #   template: src=wpa_supplicant.conf.j2
  #             dest=/etc/wpa_supplicant/wpa_supplicant.conf
  #             owner=root
  #             group=root
  #   notify: Reload WPA Supplicant
  #
  # - name : Reload WPA Supplicant
  #   command: /sbin/wpa_cli reconfigure && /sbin/wpa_cli reassociate