# playbook_install.yml
---

- hosts: gateway
  become: yes
  user: sysadm

  tasks:
  - name: Update APT package cache
    apt: update_cache=yes

  - name: Install Monitoring tools
    apt: pkg={{ item }} state=present
    with_items:
    - htop
    - iotop
    - sysstat
    - dstat
    - iftop

  - name: Install Networking tools
    apt: pkg={{ item }} state=present
    with_items:
    - iperf
    - nmap
    - tcpdump

  - name: Install Debugging tools
    apt: pkg={{ item }} state=present
    with_items:
    - dtrace

  - name: Install services & apps
    apt: pkg={{ item }} state=present
    with_items:
    - ssh
    - sudo
    - isc-dhcp-server
    - fish
#- shinken

# Configure shell fish
  - block: 
    - name: Get fish path  
      command: which fish
      register: fish

    - name: Setup fish as shell
      user: name="{{ item }}" shell="{{ fish.stdout }}"
      become_user: "{{ item }}"
      with_items:
      - {{ user_name }}
      - root

# Configure sudoer
  - name: Setup sudo for user
    set_fact: username={{ user_name }}
    lineinfile: "dest=/etc/sudoers state=present regexp='^%username' line='%username ALL=(ALL) NOPASSWD: ALL'"

# Configure Grub
  # - name: Setup grub resolution 
  #   lineinfile: "dest=/etc/default/grub state=present regexp='^%GRUB_CMDLINE_LINUX_DEFAULT' line='%username ALL=(ALL) NOPASSWD: ALL'"

  # - name: Git repository 
  #   git:  repo=https://github.com/repos/repos.git dest=/folder force=yes

  # - name: Change file right
  #   file: path=/file mode=744

  # - name: Install script
  #   command: 'python setup.py install'
  #   args:
  #     chdir: /folder


  # - name: Install requests module
  #   pip: name=requests

  # - name: Create directory
  #   file: path=/folder state=directory mode=744

  # - name: Copy file
  #   copy: src=file.py
  #         dest=/folder/file.py
  #         owner=root
  #         group=root
  #         mode=744
  #         force=yes

  # - name: Cron activation
  #   cron: name=isRunning minute="*" job="/file.sh args"