# file: roles/xebia.ntp/tasks/main
---
- name: Install NTP Service.
  apt:
    pkg: ntp
    state: present

- name: Set Localtime.
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
  when: ntp_manage_config

- name: Set Timezone.
  template:
    src: timezone.j2
    dest: /etc/timezone
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: yes
  when: ntp_manage_config

- name: Configure NTP Service.
  template: 
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ntp_manage_config
  notify: Synchronize ntp