# file: roles/xebia.dhcpd/tasks/main
---
- name: Install DHCPd.
  apt:
    name: isc-dhcp-server
    state: present

- name: Configure DHCP server.
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - "{{ dhcpd_conf_dir }}"
    - "{{ dhcpd_default_dir }}"
  notify: Restart isc-dhcp-server
  register: dhcpd_register_config
  when: dhcp_manage_config

#- name: Make sure that included files exist.
#  file:
#    path: '{{ item }}'
#    state: 'touch'
#    owner: 'root'
#    group: 'root'
#    mode: '0644'
#  with_items: dhcpd_includes
#  notify: Restart isc-dhcp-server
#  when: ((item is defined and item) and dhcpd_mode == 'server' and
#         (dhcpd_register_config is defined and dhcpd_register_config.changed))
#

- name: Make sure that IPv6 lease file exists.
  command: touch /var/lib/dhcp/dhcpd6.leases creates=/var/lib/dhcp/dhcpd6.leases
  when: dhcpd_ipversion == '6'